version: 2.0

jobs:
    build:
        docker:
            - image: cibuilds/hugo:latest
        working_directory: ~/schenk-plomer.github.io
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "bf:a6:ca:55:7b:70:23:45:5f:2a:ab:34:3e:20:2f:8f"
            - checkout
            - run:
                name: Get current site
                working_directory: ~/
                command: | 
                    git clone -b master git@github.com:schenk-plomer/schenk-plomer.github.io.git public
            - run:
                name: Generate site
                working_directory: ~/schenk-plomer.github.io
                command: HUGO_ENV=production hugo -d ~/public
            - run:
                name: Delete All SSH keys and Add the installed one
                command: ssh-add -D && ssh-add ~/.ssh/id_rsa_bfa6ca557b7023455f2aab343e202f8f
            - deploy:
                name: Deploy to Github Pages & FTP
                working_directory: ~/public
                command: |
                    git config credential.helper 'cache --timeout=120'
                    git config user.email "k@b-coding.de"
                    git config user.name "Deployment Bot"
                    git add .
                    git commit --allow-empty -m "Trigger deployment"
                    git push -q git@github.com:schenk-plomer/schenk-plomer.github.io.git master

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: src
