---
label: Service
hide_body: true
fields:
- name: header
  type: include
  config: {}
  template: titleoverlay
  label: Header
- name: intro
  type: field_group
  config: {}
  fields:
  - name: titel
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Titel
  - name: untertitel
    type: text
    config:
      required: false
    label: Untertitel
  - name: content
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Content
  - name: hintergrund
    type: file
    config:
      maxSize: 250
    label: Hintergrund
  label: Intro
- name: bereiche
  type: field_group_list
  fields:
  - name: titel
    type: text
    config:
      required: false
    label: Titel
  - name: content
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Content
  - name: icon
    type: file
    config:
      maxSize: 250
    label: Icon
  config:
    min: 
    max: 
    labelField: 
  label: Bereiche
- name: daten_and_fakten
  type: field_group
  config: {}
  fields:
  - name: titel
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Titel
  - name: bereiche
    type: field_group_list
    fields:
    - name: titel
      type: text
      config:
        required: false
      label: Titel
    - name: content
      type: textarea
      default: ''
      config:
        required: false
        wysiwyg: true
        schema:
          format: html-blocks
      label: Content
    config:
      min: 
      max: 
      labelField: 
    label: Bereiche
  label: Daten & Fakten
- name: seo
  type: include
  config: {}
  template: seo
  label: SEO
pages:
- content/service.md
