---
label: Service
hide_body: true
fields:
- name: header
  type: include
  config: {}
  template: titleoverlay
  label: Header
- name: intro
  type: field_group
  config: {}
  fields:
  - name: titel
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Titel
  - name: untertitel
    type: text
    config:
      required: false
    label: Untertitel
  - name: content
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Content
  label: Intro
